### ISSUE TITLE
Adding lang "sk" into the path of link in url field of the slide... 

### ISSUE THREAD

**Issue by dadoprom** [Pluxopolis/plxMySlippry#1]
this is ok, but it behaves like this
... each time clicking on "update image list" in administration it adds another instance of "sk" into the path. Example:

this is the correct link of article: sk/sk/article10/porod
after I click  "update image list" the link looks like this: sk/sk/sk/article10/porod

Next time I click "update image list" happens this: sk/sk/sk/sk/article10/porod

and so on...

If I want to manage for example 5 slides, with this bug it would be really tricky :D

I use pluxml 5.5 and MultiLingue - Version 0.7.4 with slovak language mutation - working on the translation...

Best regards

David

**Comment by Pluxopolis** [comment]
Hello
Be sure to use the latest version of PluXml and plugins. some various bugs were fixed
See this post: http://forum.pluxml.org/viewtopic.php?pid=52881#p52881
These updates are release candidate and will be officialy published soon
I tested with these versions and I can't see the described issue
Hope this helps

Regards
Stéphane

ps: please use rc versions if you're working on translation, otherwise there will be differences because they are changes in files. thank you
